router:
  model: gpt5nano
models:
  default:
    provider: openrouter
    id: google/gemini-2.5-flash
  gpt5nano:
    provider: openai
    id: gpt-5-nano-2025-08-07
  sonnet:
    provider: openrouter
    id: anthropic/claude-sonnet-4-5
  deepseek:
    provider: openrouter
    id: deepseek/deepseek-chat-v3.1:free
  gemini_flash:
    provider: openrouter
    id: google/gemini-2.5-flash
  glm45:
    provider: openrouter
    id: z-ai/glm-4.5
  gpt5mini:
    provider: openrouter
    id: google/gemini-2.5-flash
  haiku:
    provider: openrouter
    id: google/gemini-2.5-flash
  opus:
    provider: openrouter
    id: anthropic/claude-sonnet-4-5
  gpt4o:
    provider: openrouter
    id: anthropic/claude-sonnet-4-5
  gpt_oss_120b:
    provider: openrouter
    id: google/gemini-2.5-flash
