#!/bin/bash
# SSH Port Forwarding Setup for Mindroom Widget

echo "SSH Port Forwarding Setup for Mindroom"
echo "======================================="
echo ""
echo "You need to forward these ports from your local machine:"
echo ""
echo "1. Widget Frontend (port 3003)"
echo "2. Widget Backend (port 8765)"
echo ""
echo "Run this command on your LOCAL machine (not on the SSH server):"
echo ""
echo "ssh -L 3003:localhost:3003 -L 8765:localhost:8765 your-username@your-server"
echo ""
echo "Or if you're already connected, you can add port forwarding by:"
echo "1. Press Enter then ~C (tilde then capital C)"
echo "2. Type: -L 3003:localhost:3003"
echo "3. Press Enter"
echo "4. Type: -L 8765:localhost:8765"
echo "5. Press Enter"
echo ""
echo "Then on the server, start the services:"
echo ""
echo "# Terminal 1 - Start the backend:"
echo "cd widget/backend"
echo "source ../../.venv/bin/activate"
echo "python -m src.main"
echo ""
echo "# Terminal 2 - Start the frontend:"
echo "cd widget/frontend"
echo "pnpm run dev"
echo ""
echo "Access the app at: http://localhost:3003"
echo ""
echo "Note: Make sure CORS is configured to allow connections."
