#!/bin/bash
# Script to set up ngrok for Gmail OAuth callback

echo "Setting up ngrok for Gmail OAuth..."
echo ""
echo "1. Install ngrok if not already installed:"
echo "   wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
echo "   tar xzf ngrok-v3-stable-linux-amd64.tgz"
echo "   ./ngrok authtoken YOUR_NGROK_TOKEN"
echo ""
echo "2. Start ngrok tunnel:"
echo "   ./ngrok http 8765"
echo ""
echo "3. Copy the ngrok URL (e.g., https://abc123.ngrok.io)"
echo ""
echo "4. Update GOOGLE_REDIRECT_URI in .env:"
echo "   GOOGLE_REDIRECT_URI=https://abc123.ngrok.io/api/gmail/callback"
echo ""
echo "5. Add the same URL to Google Cloud Console:"
echo "   - Go to https://console.cloud.google.com"
echo "   - Navigate to APIs & Services > Credentials"
echo "   - Edit your OAuth 2.0 Client ID"
echo "   - Add the ngrok URL to Authorized redirect URIs"
echo "   - Save"
echo ""
echo "6. Restart the widget backend to pick up the new redirect URI"
echo ""
echo "Note: ngrok URLs change each time you restart, so you'll need to update both .env and Google Console"
