#!/bin/sh
# Test the Customer Portal and Admin Dashboard locally

echo "🎯 Testing MindRoom SaaS Panels Locally"
echo "========================================"
echo ""

# Check if services are already running
echo "Checking for running services..."
curl -s http://localhost:3002 > /dev/null 2>&1 && echo "✅ Customer Portal is running on http://localhost:3002" || echo "❌ Customer Portal not running"
curl -s http://localhost:5173 > /dev/null 2>&1 && echo "✅ Admin Dashboard is running on http://localhost:5173" || echo "❌ Admin Dashboard not running"
curl -s http://localhost:3007/health > /dev/null 2>&1 && echo "✅ Stripe Handler is running on http://localhost:3007" || echo "❌ Stripe Handler not running"

echo ""
echo "========================================"
echo "📊 Access URLs:"
echo ""
echo "Customer Portal:  http://localhost:3002"
echo "  - Sign up for new account"
echo "  - Browse pricing plans"
echo "  - Access dashboard after login"
echo ""
echo "Admin Dashboard:  http://localhost:5173"
echo "  - Monitor all customers"
echo "  - View subscription status"
echo "  - Manage instances"
echo ""
echo "Stripe Handler:   http://localhost:3007/health"
echo "  - Webhook processing"
echo "  - Payment handling"
echo ""
echo "========================================"
echo "⚡ Quick Start Commands:"
echo ""
echo "Start Customer Portal:"
echo "  cd apps/customer-portal && npm run dev"
echo ""
echo "Start Admin Dashboard:"
echo "  cd apps/admin-dashboard-fresh && npm run dev"
echo ""
echo "Start Stripe Handler:"
echo "  cd services/stripe-handler && npm start"
echo ""
echo "Test Stripe Webhooks:"
echo "  stripe listen --forward-to localhost:3007/webhooks/stripe"
