"""Released journals upgrade without reviving abandoned application work."""

from __future__ import annotations

import asyncio
import sqlite3
from contextlib import closing
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, cast
from unittest.mock import patch
from uuid import uuid4

import psycopg
import pytest

from mindroom.event_journal import (
    EventClass,
    EventJournalStore,
    EventKind,
    IngestionBatchAdmission,
    IngestionRecordAdmission,
    IngestionRecordDisposition,
    postgres_backend,
    sqlite_backend,
)
from tests.conftest import postgres_journal_schema_url
from tests.test_event_journal_store import admit, message

if TYPE_CHECKING:
    from collections.abc import Callable, Iterator
    from typing import LiteralString

_ACCOUNT = "@bot:example.org"
_SCHEMA = Path(__file__).parent / "fixtures" / "pre_nio1_journal.sql"
_OLD_EVENT = """
INSERT INTO journal_events (
    principal_id, event_id, room_id, thread_id, kind, sender, origin_server_ts,
    source_json, membership_epoch, state
) VALUES ('@bot:example.org', '$old', '!room:example.org', '', 'message', '@user:example.org',
          1, '{"type":"m.room.message","content":{"body":"Old request"}}', 7, 'pending')
"""


@dataclass(frozen=True)
class _LegacyDatabase:
    execute: Callable[[str], None]
    query: Callable[[str], list[tuple[object, ...]]]
    open: Callable[[], EventJournalStore]
    postgres: bool


@pytest.fixture(params=("sqlite", "postgres"))
def legacy_database(request: pytest.FixtureRequest, tmp_path: Path) -> Iterator[_LegacyDatabase]:
    """Create actual released DDL before any current backend opens it."""
    schema = _SCHEMA.read_text()
    if request.param == "sqlite":
        path = tmp_path / "legacy.db"

        def execute(sql: str) -> None:
            with closing(sqlite3.connect(path)) as connection:
                connection.executescript(sql)

        def query(sql: str) -> list[tuple[object, ...]]:
            with closing(sqlite3.connect(path)) as connection:
                return connection.execute(sql).fetchall()

        def opener() -> EventJournalStore:
            return EventJournalStore.open_sqlite(path)
    else:
        url = postgres_journal_schema_url(request.getfixturevalue("postgres_journal_url"))
        schema = schema.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )

        def execute(sql: str) -> None:
            with psycopg.connect(url) as connection:
                connection.execute(cast("LiteralString", sql))

        def query(sql: str) -> list[tuple[object, ...]]:
            with psycopg.connect(url) as connection:
                return connection.execute(cast("LiteralString", sql)).fetchall()

        def opener() -> EventJournalStore:
            return EventJournalStore.open_postgres(url)

    execute(schema)
    execute("INSERT INTO journal_identity VALUES (TRUE, 'original-journal-generation')")
    return _LegacyDatabase(execute, query, opener, request.param == "postgres")


@pytest.mark.asyncio
async def test_released_journal_upgrades_and_preserves_new_work(legacy_database: _LegacyDatabase) -> None:
    """Upgrade preserves identity/history, abandons pending work, and runs only once."""
    legacy_database.execute(_OLD_EVENT)
    legacy_database.execute("""
        INSERT INTO visible_messages VALUES (
            '@bot:example.org', '!room:example.org', '$old', '', '@user:example.org', 1,
            '$old', 1, '{"body":"Old request","msgtype":"m.text"}', NULL, 7);
        INSERT INTO room_membership VALUES ('@bot:example.org', '!room:example.org', 7, 0, 2);
        INSERT INTO matrix_delivery_outbox (
            principal_id, delivery_id, stage, event_type, room_id, membership_epoch, thread_id,
            transaction_id, payload_json, attempted, sending_device_id, created_at_ns
        ) VALUES ('@bot:example.org', '$old', 'initial', 'm.room.message', '!room:example.org', 7,
                  '', 'old-transaction', '{}', 1, 'OLD_DEVICE', 1);
        INSERT INTO approval_continuations (
            principal_id, approval_id, entity_name, state, context_json, created_at_ns
        ) VALUES ('@bot:example.org', 'old-approval', 'bot', 'claimed', '{}', 1);
        INSERT INTO approval_continuation_sources VALUES ('@bot:example.org', 'old-approval', '$old', 0);
        INSERT INTO turn_records VALUES (
            'bot', '$completed', '$completed',
            '{"anchor_event_id":"$completed","source_event_ids":["$completed"],"completed":true,"response_event_id":"$response","timestamp":1}'
        );
    """)
    store = legacy_database.open()
    try:
        assert await store.existing_generation() == "original-journal-generation"
        principal = store.principal(_ACCOUNT)
        assert not await principal.pending()
        assert await principal.approval_continuation("old-approval") is None
        assert not await principal.owns_matrix_response(room_id="!room:example.org", event_id="$old")
        assert await store.backend.read(lambda tx: tx.fetchall("SELECT * FROM matrix_delivery_outbox")) == ()
        history = await store.backend.read(lambda tx: tx.fetchone("SELECT content_json FROM visible_messages"))
        assert history is not None
        assert "Old request" in history["content_json"]
        assert await store.backend.read(lambda tx: tx.fetchone("SELECT record_json FROM turn_records")) is not None
        consumer = await principal.load_or_create_ingestion_consumer(new_generation=uuid4())
        stream = uuid4()
        await principal.bind_ingestion_stream(generation=consumer.generation, stream_id=stream)
        await admit(principal, "$new")
    finally:
        await store.close()

    reopened = legacy_database.open()
    try:
        principal = reopened.principal(_ACCOUNT)
        assert [event.event_id for event in await principal.pending()] == ["$new"]
        restored = await principal.load_or_create_ingestion_consumer(new_generation=uuid4())
        assert restored.generation == consumer.generation
        assert restored.stream_id == stream
        assert await reopened.existing_generation() == "original-journal-generation"
    finally:
        await reopened.close()


@pytest.mark.asyncio
@pytest.mark.parametrize("old_epoch", [0, 7])
async def test_upgrade_preserves_pending_history_repair(legacy_database: _LegacyDatabase, old_epoch: int) -> None:
    """An unresolved historical body stays repairable after membership is rebased."""
    legacy_database.execute(_OLD_EVENT)
    legacy_database.execute(f"""
        INSERT INTO visible_messages VALUES (
            '@bot:example.org', '!room:example.org', '$old', '', '@user:example.org', 1,
            '$old', 1, NULL, 37, {old_epoch});
    """)  # noqa: S608 -- epoch is a fixed test parameter
    store = legacy_database.open()
    try:
        page = await store.principal(_ACCOUNT).read_conversation(room_id="!room:example.org", thread_id=None, limit=10)
        assert not page.messages
        (repair,) = page.refresh_pending
        assert repair.membership_epoch == 0
    finally:
        await store.close()

    reopened = legacy_database.open()
    try:
        principal = reopened.principal(_ACCOUNT)
        assert await principal.install_refetched_revision(
            repair,
            revision_event_id="$old",
            revision_ts=1,
            revision_sender="@user:example.org",
            content={"body": "Recovered historical body", "msgtype": "m.text"},
        )
        page = await principal.read_conversation(room_id="!room:example.org", thread_id=None, limit=10)
        assert not page.refresh_pending
        assert [message.content["body"] for message in page.messages] == ["Recovered historical body"]
        assert not await principal.pending()
    finally:
        await reopened.close()


@pytest.mark.asyncio
@pytest.mark.parametrize("old_state", ["pending", "settled"])
@pytest.mark.parametrize("event_class", [EventClass.CONTEXT_ONLY, EventClass.ACTIONABLE])
async def test_upgrade_keeps_late_decrypted_history_silent(
    legacy_database: _LegacyDatabase,
    old_state: str,
    event_class: EventClass,
) -> None:
    """Old unreadable identities accept later plaintext without owning a new turn."""
    legacy_database.execute(
        _OLD_EVENT.replace("'message'", "'decryption_failure'").replace("'pending'", f"'{old_state}'"),
    )
    stream = uuid4()
    for sequence in (1, 2):
        store = legacy_database.open()
        try:
            principal = store.principal(_ACCOUNT)
            old = await principal.load_event("$old")
            assert old is not None
            assert old.kind is EventKind.OPAQUE_HISTORY
            consumer = await principal.load_or_create_ingestion_consumer(new_generation=uuid4())
            await principal.bind_ingestion_stream(generation=consumer.generation, stream_id=stream)
            event, projected = message(
                "$old",
                room_id="!room:example.org",
                sender="@user:example.org",
                ts=1,
                event_class=event_class,
                content={"body": "Decrypted old text", "msgtype": "m.text"},
            )
            facts = await principal.admit_ingestion_batch(
                IngestionBatchAdmission(
                    stream,
                    sequence,
                    (
                        IngestionRecordAdmission(
                            IngestionRecordDisposition.SEMANTIC_EVENT,
                            event=event,
                            projected=projected,
                        ),
                    ),
                ),
            )
            assert not facts.semantic_event_new
            assert not await principal.pending()
            page = await principal.read_conversation(room_id="!room:example.org", thread_id=None, limit=10)
            assert [item.content["body"] for item in page.messages] == ["Decrypted old text"]
        finally:
            await store.close()


@pytest.mark.asyncio
async def test_clean_released_journal_needs_no_manual_adoption(legacy_database: _LegacyDatabase) -> None:
    """A journal with no unfinished work still upgrades instead of crashing startup."""
    legacy_database.execute(_OLD_EVENT.replace("'pending'", "'settled'"))
    store = legacy_database.open()
    try:
        assert await store.existing_generation() == "original-journal-generation"
        assert not await store.principal(_ACCOUNT).pending()
    finally:
        await store.close()


@pytest.mark.asyncio
async def test_interrupted_upgrade_rolls_back_and_retries(legacy_database: _LegacyDatabase) -> None:
    """Failed DDL cannot publish the new marker while abandoning only part of old work."""
    legacy_database.execute(_OLD_EVENT)
    module = postgres_backend if legacy_database.postgres else sqlite_backend
    original = module.schema_statements
    with (
        patch.object(
            module,
            "schema_statements",
            side_effect=lambda dialect: (*original(dialect), "INVALID UPGRADE SQL"),
        ),
        pytest.raises((sqlite3.OperationalError, psycopg.errors.SyntaxError)),
    ):
        legacy_database.open()
    assert legacy_database.query("SELECT state, membership_epoch FROM journal_events") == [("pending", 7)]
    assert legacy_database.query("SELECT generation FROM journal_identity") == [("original-journal-generation",)]
    marker_query = (
        "SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() "
        "AND table_name = 'matrix_sync_consumers'"
        if legacy_database.postgres
        else "SELECT name FROM sqlite_master WHERE name = 'matrix_sync_consumers'"
    )
    assert legacy_database.query(marker_query) == []
    store = legacy_database.open()
    try:
        assert not await store.principal(_ACCOUNT).pending()
    finally:
        await store.close()


@pytest.mark.asyncio
async def test_concurrent_startups_share_one_upgrade(legacy_database: _LegacyDatabase) -> None:
    """Competing schema openers preserve one generation and one consumer binding."""
    legacy_database.execute(_OLD_EVENT)
    first, second = await asyncio.gather(*(asyncio.to_thread(legacy_database.open) for _ in range(2)))
    try:
        consumers = await asyncio.gather(
            first.principal(_ACCOUNT).load_or_create_ingestion_consumer(new_generation=uuid4()),
            second.principal(_ACCOUNT).load_or_create_ingestion_consumer(new_generation=uuid4()),
        )
        assert consumers[0] == consumers[1]
        assert not await first.principal(_ACCOUNT).pending()
        assert await second.existing_generation() == "original-journal-generation"
    finally:
        await first.close()
        await second.close()
