"""Released journals upgrade without reviving abandoned application work."""

from __future__ import annotations

import asyncio
import sqlite3
from contextlib import closing
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, cast
from unittest.mock import patch
from uuid import uuid4

import psycopg
import pytest

from mindroom import reply_lifecycle as rl
from mindroom.event_journal import (
    DeliveryStage,
    EventClass,
    EventJournalStore,
    EventKind,
    IngestionBatchAdmission,
    IngestionRecordAdmission,
    IngestionRecordDisposition,
    postgres_backend,
    sqlite_backend,
)
from mindroom.response_sources import ResponseSources
from tests.conftest import postgres_journal_schema_url
from tests.test_event_journal_store import admit, message

if TYPE_CHECKING:
    from collections.abc import Callable, Iterator
    from typing import LiteralString

_ACCOUNT = "@bot:example.org"
_SCHEMA = Path(__file__).parent / "fixtures" / "pre_nio1_journal.sql"
_OLD_EVENT = """
INSERT INTO journal_events (
    principal_id, event_id, room_id, thread_id, kind, sender, origin_server_ts,
    source_json, membership_epoch, state
) VALUES ('@bot:example.org', '$old', '!room:example.org', '', 'message', '@user:example.org',
          1, '{"type":"m.room.message","content":{"body":"Old request"}}', 7, 'pending')
"""


@dataclass(frozen=True)
class _LegacyDatabase:
    execute: Callable[[str], None]
    query: Callable[[str], list[tuple[object, ...]]]
    open: Callable[[], EventJournalStore]
    postgres: bool


@pytest.fixture(params=("sqlite", "postgres"))
def legacy_database(request: pytest.FixtureRequest, tmp_path: Path) -> Iterator[_LegacyDatabase]:
    """Create actual released DDL before any current backend opens it."""
    schema = _SCHEMA.read_text()
    if request.param == "sqlite":
        path = tmp_path / "legacy.db"

        def execute(sql: str) -> None:
            with closing(sqlite3.connect(path)) as connection:
                connection.executescript(sql)

        def query(sql: str) -> list[tuple[object, ...]]:
            with closing(sqlite3.connect(path)) as connection:
                return connection.execute(sql).fetchall()

        def opener() -> EventJournalStore:
            return EventJournalStore.open_sqlite(path)
    else:
        url = postgres_journal_schema_url(request.getfixturevalue("postgres_journal_url"))
        schema = schema.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )

        def execute(sql: str) -> None:
            with psycopg.connect(url) as connection:
                connection.execute(cast("LiteralString", sql))

        def query(sql: str) -> list[tuple[object, ...]]:
            with psycopg.connect(url) as connection:
                return connection.execute(cast("LiteralString", sql)).fetchall()

        def opener() -> EventJournalStore:
            return EventJournalStore.open_postgres(url)

    execute(schema)
    execute("INSERT INTO journal_identity VALUES (TRUE, 'original-journal-generation')")
    return _LegacyDatabase(execute, query, opener, request.param == "postgres")


@pytest.mark.asyncio
async def test_released_journal_upgrades_and_preserves_new_work(legacy_database: _LegacyDatabase) -> None:
    """Upgrade preserves identity/history, abandons pending work, and runs only once."""
    legacy_database.execute(_OLD_EVENT)
    legacy_database.execute("""
        INSERT INTO visible_messages VALUES (
            '@bot:example.org', '!room:example.org', '$old', '', '@user:example.org', 1,
            '$old', 1, '{"body":"Old request","msgtype":"m.text"}', NULL, 7);
        INSERT INTO room_membership VALUES ('@bot:example.org', '!room:example.org', 7, 0, 2);
        INSERT INTO matrix_delivery_outbox (
            principal_id, delivery_id, stage, event_type, room_id, membership_epoch, thread_id,
            transaction_id, payload_json, attempted, sending_device_id, created_at_ns
        ) VALUES ('@bot:example.org', '$old', 'initial', 'm.room.message', '!room:example.org', 7,
                  '', 'old-transaction', '{}', 1, 'OLD_DEVICE', 1);
        INSERT INTO approval_continuations (
            principal_id, approval_id, entity_name, state, context_json, created_at_ns
        ) VALUES ('@bot:example.org', 'old-approval', 'bot', 'claimed', '{}', 1);
        INSERT INTO approval_continuation_sources VALUES ('@bot:example.org', 'old-approval', '$old', 0);
        INSERT INTO turn_records VALUES (
            'bot', '$completed', '$completed',
            '{"anchor_event_id":"$completed","source_event_ids":["$completed"],"completed":true,"response_event_id":"$response","timestamp":1}'
        );
    """)
    store = legacy_database.open()
    try:
        assert await store.existing_generation() == "original-journal-generation"
        principal = store.principal(_ACCOUNT)
        assert not await principal.pending()
        assert await principal.approval_continuation("old-approval") is None
        assert await store.backend.read(lambda tx: tx.fetchall("SELECT * FROM matrix_delivery_outbox")) == ()
        history = await store.backend.read(lambda tx: tx.fetchone("SELECT content_json FROM visible_messages"))
        assert history is not None
        assert "Old request" in history["content_json"]
        assert await store.backend.read(lambda tx: tx.fetchone("SELECT record_json FROM turn_records")) is not None
        consumer = await principal.load_or_create_ingestion_consumer(new_generation=uuid4())
        stream = uuid4()
        await principal.bind_ingestion_stream(generation=consumer.generation, stream_id=stream)
        await admit(principal, "$new")
    finally:
        await store.close()

    reopened = legacy_database.open()
    try:
        principal = reopened.principal(_ACCOUNT)
        assert [event.event_id for event in await principal.pending()] == ["$new"]
        restored = await principal.load_or_create_ingestion_consumer(new_generation=uuid4())
        assert restored.generation == consumer.generation
        assert restored.stream_id == stream
        assert await reopened.existing_generation() == "original-journal-generation"
    finally:
        await reopened.close()


@pytest.mark.asyncio
@pytest.mark.parametrize("old_epoch", [0, 7])
async def test_upgrade_preserves_pending_history_repair(legacy_database: _LegacyDatabase, old_epoch: int) -> None:
    """An unresolved historical body stays repairable after membership is rebased."""
    legacy_database.execute(_OLD_EVENT)
    legacy_database.execute(f"""
        INSERT INTO visible_messages VALUES (
            '@bot:example.org', '!room:example.org', '$old', '', '@user:example.org', 1,
            '$old', 1, NULL, 37, {old_epoch});
    """)  # noqa: S608 -- epoch is a fixed test parameter
    store = legacy_database.open()
    try:
        page = await store.principal(_ACCOUNT).read_conversation(room_id="!room:example.org", thread_id=None, limit=10)
        assert not page.messages
        (repair,) = page.refresh_pending
        assert repair.membership_epoch == 0
    finally:
        await store.close()

    reopened = legacy_database.open()
    try:
        principal = reopened.principal(_ACCOUNT)
        assert await principal.install_refetched_revision(
            repair,
            revision_event_id="$old",
            revision_ts=1,
            revision_sender="@user:example.org",
            content={"body": "Recovered historical body", "msgtype": "m.text"},
        )
        page = await principal.read_conversation(room_id="!room:example.org", thread_id=None, limit=10)
        assert not page.refresh_pending
        assert [message.content["body"] for message in page.messages] == ["Recovered historical body"]
        assert not await principal.pending()
    finally:
        await reopened.close()


@pytest.mark.asyncio
@pytest.mark.parametrize("old_state", ["pending", "settled"])
@pytest.mark.parametrize("event_class", [EventClass.CONTEXT_ONLY, EventClass.ACTIONABLE])
async def test_upgrade_keeps_late_decrypted_history_silent(
    legacy_database: _LegacyDatabase,
    old_state: str,
    event_class: EventClass,
) -> None:
    """Old unreadable identities accept later plaintext without owning a new turn."""
    legacy_database.execute(
        _OLD_EVENT.replace("'message'", "'decryption_failure'").replace("'pending'", f"'{old_state}'"),
    )
    stream = uuid4()
    for sequence in (1, 2):
        store = legacy_database.open()
        try:
            principal = store.principal(_ACCOUNT)
            old = await principal.load_event("$old")
            assert old is not None
            assert old.kind is EventKind.OPAQUE_HISTORY
            consumer = await principal.load_or_create_ingestion_consumer(new_generation=uuid4())
            await principal.bind_ingestion_stream(generation=consumer.generation, stream_id=stream)
            event, projected = message(
                "$old",
                room_id="!room:example.org",
                sender="@user:example.org",
                ts=1,
                event_class=event_class,
                content={"body": "Decrypted old text", "msgtype": "m.text"},
            )
            facts = await principal.admit_ingestion_batch(
                IngestionBatchAdmission(
                    stream,
                    sequence,
                    (
                        IngestionRecordAdmission(
                            IngestionRecordDisposition.SEMANTIC_EVENT,
                            event=event,
                            projected=projected,
                        ),
                    ),
                ),
            )
            assert not facts.semantic_event_new
            assert not await principal.pending()
            page = await principal.read_conversation(room_id="!room:example.org", thread_id=None, limit=10)
            assert [item.content["body"] for item in page.messages] == ["Decrypted old text"]
        finally:
            await store.close()


@pytest.mark.asyncio
async def test_clean_released_journal_needs_no_manual_adoption(legacy_database: _LegacyDatabase) -> None:
    """A journal with no unfinished work still upgrades instead of crashing startup."""
    legacy_database.execute(_OLD_EVENT.replace("'pending'", "'settled'"))
    store = legacy_database.open()
    try:
        assert await store.existing_generation() == "original-journal-generation"
        assert not await store.principal(_ACCOUNT).pending()
    finally:
        await store.close()


@pytest.mark.asyncio
async def test_interrupted_upgrade_rolls_back_and_retries(legacy_database: _LegacyDatabase) -> None:
    """Failed DDL cannot publish the new marker while abandoning only part of old work."""
    legacy_database.execute(_OLD_EVENT)
    module = postgres_backend if legacy_database.postgres else sqlite_backend
    original = module.schema_statements
    with (
        patch.object(
            module,
            "schema_statements",
            side_effect=lambda dialect: (*original(dialect), "INVALID UPGRADE SQL"),
        ),
        pytest.raises((sqlite3.OperationalError, psycopg.errors.SyntaxError)),
    ):
        legacy_database.open()
    assert legacy_database.query("SELECT state, membership_epoch FROM journal_events") == [("pending", 7)]
    assert legacy_database.query("SELECT generation FROM journal_identity") == [("original-journal-generation",)]
    marker_query = (
        "SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() "
        "AND table_name = 'matrix_sync_consumers'"
        if legacy_database.postgres
        else "SELECT name FROM sqlite_master WHERE name = 'matrix_sync_consumers'"
    )
    assert legacy_database.query(marker_query) == []
    store = legacy_database.open()
    try:
        assert not await store.principal(_ACCOUNT).pending()
    finally:
        await store.close()


@pytest.mark.asyncio
async def test_concurrent_startups_share_one_upgrade(legacy_database: _LegacyDatabase) -> None:
    """Competing schema openers preserve one generation and one consumer binding."""
    legacy_database.execute(_OLD_EVENT)
    first, second = await asyncio.gather(*(asyncio.to_thread(legacy_database.open) for _ in range(2)))
    try:
        consumers = await asyncio.gather(
            first.principal(_ACCOUNT).load_or_create_ingestion_consumer(new_generation=uuid4()),
            second.principal(_ACCOUNT).load_or_create_ingestion_consumer(new_generation=uuid4()),
        )
        assert consumers[0] == consumers[1]
        assert not await first.principal(_ACCOUNT).pending()
        assert await second.existing_generation() == "original-journal-generation"
    finally:
        await first.close()
        await second.close()


_PRE_REPLY_OUTBOX = """
CREATE TABLE matrix_delivery_outbox (
    principal_id TEXT NOT NULL,
    delivery_id TEXT NOT NULL,
    stage TEXT NOT NULL CHECK (stage IN ('initial', 'final')),
    event_type TEXT NOT NULL,
    room_id TEXT NOT NULL,
    membership_epoch BIGINT NOT NULL,
    thread_id TEXT NOT NULL,
    transaction_id TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    result_json TEXT,
    edits_event_id TEXT,
    edit_target_pending INTEGER NOT NULL DEFAULT 0,
    attempted INTEGER NOT NULL DEFAULT 0,
    retired INTEGER NOT NULL DEFAULT 0,
    permanent_failure_reason TEXT,
    sending_device_id TEXT,
    acknowledged_event_id TEXT,
    created_at_ns BIGINT NOT NULL,
    PRIMARY KEY (principal_id, delivery_id, stage)
)
"""
_PRE_REPLY_OUTBOX_COLUMNS = (
    "principal_id, delivery_id, stage, event_type, room_id, membership_epoch, thread_id, transaction_id, "
    "payload_json, result_json, edits_event_id, edit_target_pending, attempted, retired, "
    "permanent_failure_reason, sending_device_id, acknowledged_event_id, created_at_ns"
)


@pytest.mark.asyncio
async def test_outbox_upgrade_keeps_rows_and_admits_edit_stage(legacy_database: _LegacyDatabase) -> None:
    """An outbox from before reply rows keeps every row and accepts the reply stage and columns."""
    store = legacy_database.open()
    principal = store.principal("agent@alice")
    await admit(principal, "$source")
    assert await principal.enqueue_matrix_delivery(
        delivery_id="$source",
        stage=DeliveryStage.FINAL,
        room_id="!room:example.org",
        thread_id=None,
        payload={"body": "answer"},
    )
    await store.close()
    legacy_database.execute(
        "ALTER TABLE matrix_delivery_outbox RENAME TO outbox_current;"  # noqa: S608 - fixed test DDL
        f"{_PRE_REPLY_OUTBOX};"
        f"INSERT INTO matrix_delivery_outbox ({_PRE_REPLY_OUTBOX_COLUMNS}) "
        f"SELECT {_PRE_REPLY_OUTBOX_COLUMNS} FROM outbox_current;"
        "DROP TABLE outbox_current;",
    )

    for _ in range(2):
        store = legacy_database.open()
        try:
            delivery = await store.principal("agent@alice").load_matrix_delivery(
                delivery_id="$source",
                stage=DeliveryStage.FINAL,
            )
        finally:
            await store.close()
        assert delivery is not None
        assert delivery.payload["body"] == "answer"
    legacy_database.execute(
        "INSERT INTO matrix_delivery_outbox ("  # noqa: S608 - fixed test DDL
        f"{_PRE_REPLY_OUTBOX_COLUMNS}, reply_id, span_id, reply_sequence) "
        "SELECT principal_id, delivery_id || ':edit:1', 'edit', event_type, room_id, membership_epoch, thread_id, "
        "transaction_id, payload_json, result_json, edits_event_id, edit_target_pending, attempted, retired, "
        "permanent_failure_reason, sending_device_id, acknowledged_event_id, created_at_ns, 'reply-1', 'span-1', 1 "
        "FROM matrix_delivery_outbox WHERE stage = 'final'",
    )
    assert legacy_database.query(
        "SELECT stage, reply_id, reply_sequence FROM matrix_delivery_outbox ORDER BY stage",
    ) == [("edit", "reply-1", 1), ("final", None, None)]
    indexes = (
        legacy_database.query("SELECT indexname FROM pg_indexes WHERE tablename = 'matrix_delivery_outbox'")
        if legacy_database.postgres
        else legacy_database.query(
            "SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = 'matrix_delivery_outbox'",
        )
    )
    assert ("matrix_delivery_outbox_reply",) in indexes
    assert ("matrix_delivery_outbox_unacknowledged_scan",) in indexes
    with pytest.raises((sqlite3.IntegrityError, psycopg.errors.CheckViolation)):
        legacy_database.execute(
            "UPDATE matrix_delivery_outbox SET stage = 'bogus' WHERE stage = 'final'",
        )


# The reply tables as v2026.10.228 through v2026.10.235 created them.
_PRE_WAIT_REPLY_MESSAGES = """
CREATE TABLE reply_messages (
    principal_id TEXT NOT NULL,
    reply_id TEXT NOT NULL,
    entity_name TEXT NOT NULL,
    room_id TEXT NOT NULL,
    thread_id TEXT,
    membership_epoch BIGINT NOT NULL,
    event_id TEXT,
    state TEXT NOT NULL CHECK (state IN ('active', 'paused', 'completed', 'cancelled', 'failed', 'gone')),
    current_span_id TEXT,
    last_span_id TEXT NOT NULL,
    presentation_json TEXT NOT NULL,
    possibly_shown_json TEXT,
    confirmed_seq BIGINT,
    revision BIGINT NOT NULL,
    placeholder_only BOOLEAN NOT NULL,
    stop_receipt_order BIGINT,
    stop_applied_receipt_order BIGINT,
    stop_button_event_id TEXT,
    redaction_pending_json TEXT,
    owed_write_json TEXT,
    reply_sequence BIGINT NOT NULL,
    created_at_ns BIGINT NOT NULL,
    updated_at_ns BIGINT NOT NULL,
    PRIMARY KEY (principal_id, reply_id),
    UNIQUE (principal_id, event_id)
)
"""
_PRE_WAKE_REPLY_SPANS = """
CREATE TABLE reply_spans (
    principal_id TEXT NOT NULL,
    span_id TEXT NOT NULL,
    reply_id TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('turn', 'replay', 'approval_resume', 'regeneration')),
    delivery_id TEXT NOT NULL,
    approval_id TEXT,
    bot_generation TEXT NOT NULL,
    base_sequence BIGINT NOT NULL,
    rollback_json TEXT,
    outcome TEXT CHECK (outcome IN (
        'completed', 'paused', 'cancelled', 'failed',
        'suppressed', 'restored', 'released', 'superseded', 'lost')),
    claimed_at_ns BIGINT NOT NULL,
    PRIMARY KEY (principal_id, span_id)
)
"""
_PRE_WAIT_REPLY_COLUMNS = (
    "principal_id, reply_id, entity_name, room_id, thread_id, membership_epoch, event_id, state, current_span_id, "
    "last_span_id, presentation_json, possibly_shown_json, confirmed_seq, revision, placeholder_only, "
    "stop_receipt_order, stop_applied_receipt_order, stop_button_event_id, redaction_pending_json, owed_write_json, "
    "reply_sequence, created_at_ns, updated_at_ns"
)
_PRE_WAKE_SPAN_COLUMNS = (
    "principal_id, span_id, reply_id, kind, delivery_id, approval_id, bot_generation, base_sequence, rollback_json, "
    "outcome, claimed_at_ns"
)


@pytest.mark.asyncio
async def test_reply_upgrade_keeps_rows_and_admits_waiting_and_wake(legacy_database: _LegacyDatabase) -> None:
    """Reply tables from before background-work waits keep every row and accept waiting replies and wake spans."""
    store = legacy_database.open()
    principal = store.principal("agent@alice")
    request = rl.ClaimRequest(
        span_id="span-1",
        delivery_id="$source",
        sources=ResponseSources(pending_event_ids=("$source",), logical_source_event_ids=("$source",)),
        bot_generation="gen-1",
        now_ns=10,
        new_reply_id="reply-1",
        entity_name="agent",
        room_id="!room:example.org",
        thread_id=None,
        membership_epoch=0,
        empty_presentation="{}",
    )
    await admit(principal, "$source")
    claimed = (await principal.replies.claim(request)).transition
    assert claimed.reply is not None
    await store.close()
    for table, ddl, columns in (
        ("reply_messages", _PRE_WAIT_REPLY_MESSAGES, _PRE_WAIT_REPLY_COLUMNS),
        ("reply_spans", _PRE_WAKE_REPLY_SPANS, _PRE_WAKE_SPAN_COLUMNS),
    ):
        legacy_database.execute(
            f"ALTER TABLE {table} RENAME TO {table}_current;"  # noqa: S608 - fixed test DDL
            f"DROP INDEX IF EXISTS reply_messages_waiting;"
            f"{ddl};"
            f"INSERT INTO {table} ({columns}) SELECT {columns} FROM {table}_current;"
            f"DROP TABLE {table}_current;",
        )

    for _ in range(2):
        store = legacy_database.open()
        try:
            reply = await store.principal("agent@alice").replies.load("reply-1")
        finally:
            await store.close()
        assert reply == claimed.reply
    legacy_database.execute("UPDATE reply_messages SET state = 'waiting', hold_key = 'key' WHERE reply_id = 'reply-1'")
    legacy_database.execute("UPDATE reply_spans SET kind = 'wake' WHERE span_id = 'span-1'")
    indexes = (
        legacy_database.query("SELECT indexname FROM pg_indexes WHERE tablename = 'reply_messages'")
        if legacy_database.postgres
        else legacy_database.query(
            "SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = 'reply_messages'",
        )
    )
    assert ("reply_messages_waiting",) in indexes
    assert ("reply_messages_room",) in indexes
    with pytest.raises((sqlite3.IntegrityError, psycopg.errors.CheckViolation)):
        legacy_database.execute("UPDATE reply_messages SET state = 'bogus' WHERE reply_id = 'reply-1'")
    with pytest.raises((sqlite3.IntegrityError, psycopg.errors.CheckViolation)):
        legacy_database.execute("UPDATE reply_spans SET kind = 'bogus' WHERE span_id = 'span-1'")
