name: Build Docker Images
# Builds images in parallel for maximum speed with change detection

on:
  push:
    branches: [ main, public ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'deploy/Dockerfile.*'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.gitea/workflows/**'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build all images'
        type: boolean
        default: false

env:
  REGISTRY: git.nijho.lt
  OWNER: basnijholt

jobs:
  # Build each image/platform combination in parallel
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        image:
          - backend
          - frontend
        platform:
          - linux/amd64
          # Skip ARM64 for now to save time and resources
          # - linux/arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU (for ARM64 builds)
      if: matrix.platform == 'linux/arm64'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
        driver-opts: |
          network=host

    - name: Login to Gitea Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ gitea.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set build vars
      id: vars
      run: |
        # Set dockerfile path
        echo "dockerfile=deploy/Dockerfile.${{ matrix.image }}" >> $GITHUB_OUTPUT

        # Set platform suffix
        if [ "${{ matrix.platform }}" = "linux/amd64" ]; then
          echo "platform_suffix=amd64" >> $GITHUB_OUTPUT
        else
          echo "platform_suffix=arm64" >> $GITHUB_OUTPUT
        fi

        # No special build args needed
        echo "build_args=" >> $GITHUB_OUTPUT

        # Generate timestamp
        echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Build and push platform image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ steps.vars.outputs.dockerfile }}
        platforms: ${{ matrix.platform }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:${{ steps.vars.outputs.platform_suffix }}
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:${{ github.ref_name }}-${{ steps.vars.outputs.platform_suffix }}
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:${{ steps.vars.outputs.timestamp }}-${{ steps.vars.outputs.platform_suffix }}
        build-args: ${{ steps.vars.outputs.build_args }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:buildcache-${{ steps.vars.outputs.platform_suffix }}
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:buildcache-${{ steps.vars.outputs.platform_suffix }},mode=max
        provenance: false
        sbom: false

  # Create multi-arch manifests after all builds complete
  manifest:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        image:
          - backend
          - frontend

    steps:
    - name: Login to Gitea Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ gitea.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Create and push manifest
      run: |
        # Create multi-arch manifest
        docker manifest create \
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:latest \
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:amd64 \
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:arm64

        # Push manifest
        docker manifest push ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:latest

        # Also create branch-tagged manifest
        docker manifest create \
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:${{ github.ref_name }} \
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:${{ github.ref_name }}-amd64 \
          ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:${{ github.ref_name }}-arm64

        docker manifest push ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:${{ github.ref_name }}

        echo "✅ Multi-arch manifest created for mindroom-${{ matrix.image }}"
        echo "Pull with: docker pull ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-${{ matrix.image }}:latest"
