name: Docker Build Test (Full Pipeline)

on:
  workflow_dispatch:  # Manual trigger only for debugging

env:
  REGISTRY: git.nijho.lt
  OWNER: basnijholt

jobs:
  test-full-pipeline:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        component: [backend, frontend]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU (for multi-arch)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Gitea Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ gitea.actor }}
        password: ${{ secrets.GITEA_TOKEN }}

    - name: Create test Dockerfile for ${{ matrix.component }}
      run: |
        if [ "${{ matrix.component }}" = "backend" ]; then
          cat > Dockerfile.test-${{ matrix.component }} << 'EOF'
        FROM python:3.11-slim
        WORKDIR /app
        RUN echo "import sys; print('Test backend running')" > app.py
        CMD ["python", "app.py"]
        EOF
        else
          cat > Dockerfile.test-${{ matrix.component }} << 'EOF'
        FROM node:18-alpine
        WORKDIR /app
        RUN echo "console.log('Test frontend running');" > app.js
        CMD ["node", "app.js"]
        EOF
        fi

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-test-${{ matrix.component }}
        tags: |
          type=raw,value=test-latest
          type=raw,value=test-${{ github.run_number }}

    - name: Build and push test ${{ matrix.component }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.test-${{ matrix.component }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-test-${{ matrix.component }}:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-test-${{ matrix.component }}:buildcache,mode=max

    - name: Test image
      run: |
        echo "Testing ${{ matrix.component }} image..."
        docker pull ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-test-${{ matrix.component }}:test-latest
        docker run --rm ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-test-${{ matrix.component }}:test-latest
        echo "✅ ${{ matrix.component }} test successful!"
