name: Build Multi-Arch Docker Images
# Builds multi-arch images for both backend and frontend

on:
  push:
    branches: [ main, public ]
  workflow_dispatch:  # Allow manual triggers
    inputs:
      build_backend:
        description: 'Build backend image'
        type: boolean
        default: true
      build_frontend:
        description: 'Build frontend image'
        type: boolean
        default: true

env:
  REGISTRY: git.nijho.lt
  OWNER: basnijholt

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: deploy/Dockerfile.backend
            image: mindroom-backend
            build-args: ""
          - name: frontend
            dockerfile: deploy/Dockerfile.frontend
            image: mindroom-frontend
            build-args: |
              NODE_OPTIONS=--max-old-space-size=6144
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check if should build
      id: should-build
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          if [ "${{ matrix.name }}" = "backend" ] && [ "${{ github.event.inputs.build_backend }}" = "false" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.name }}" = "frontend" ] && [ "${{ github.event.inputs.build_frontend }}" = "false" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Set up QEMU
      if: steps.should-build.outputs.skip != 'true'
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      if: steps.should-build.outputs.skip != 'true'
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
        driver-opts: |
          network=host
    
    - name: Login to Gitea Registry
      if: steps.should-build.outputs.skip != 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ gitea.actor }}
        password: ${{ secrets.GITEA_TOKEN }}
    
    - name: Extract metadata
      if: steps.should-build.outputs.skip != 'true'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.image }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
    
    - name: Build and push
      if: steps.should-build.outputs.skip != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ matrix.build-args }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.image }}:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.image }}:buildcache,mode=max
        provenance: false
        sbom: false
    
    - name: Print image URLs
      if: steps.should-build.outputs.skip != 'true'
      run: |
        echo "✅ Image pushed successfully!"
        echo "Pull commands:"
        echo "  docker pull ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.image }}:latest"
        echo "  docker pull ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.image }}:${{ github.ref_name }}"