name: Smart Build (Only Changed)

on:
  push:
    branches: [ main, public ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'deploy/Dockerfile.*'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.gitea/workflows/**'

env:
  REGISTRY: git.nijho.lt
  OWNER: basnijholt

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Detect changes
      id: changes
      run: |
        echo "Checking for changes..."
        
        # Get list of changed files
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD || git diff --name-only HEAD)
        
        # Check for backend changes
        if echo "$CHANGED_FILES" | grep -qE "(backend/|pyproject.toml|uv.lock|deploy/Dockerfile.backend)"; then
          echo "backend=true" >> $GITHUB_OUTPUT
          echo "✅ Backend changes detected"
        else
          echo "backend=false" >> $GITHUB_OUTPUT
          echo "⏩ No backend changes"
        fi
        
        # Check for frontend changes
        if echo "$CHANGED_FILES" | grep -qE "(frontend/|deploy/Dockerfile.frontend)"; then
          echo "frontend=true" >> $GITHUB_OUTPUT
          echo "✅ Frontend changes detected"
        else
          echo "frontend=false" >> $GITHUB_OUTPUT
          echo "⏩ No frontend changes"
        fi

  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: docker/setup-qemu-action@v3
    
    - uses: docker/setup-buildx-action@v3
    
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ gitea.actor }}
        password: ${{ secrets.GITEA_TOKEN }}
    
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-backend
        tags: |
          type=raw,value=latest
          type=sha,prefix={{branch}}-
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
    
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: deploy/Dockerfile.backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-backend:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-backend:buildcache,mode=max

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: docker/setup-qemu-action@v3
    
    - uses: docker/setup-buildx-action@v3
    
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ gitea.actor }}
        password: ${{ secrets.GITEA_TOKEN }}
    
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-frontend
        tags: |
          type=raw,value=latest
          type=sha,prefix={{branch}}-
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
    
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: deploy/Dockerfile.frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          NODE_OPTIONS=--max-old-space-size=6144
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-frontend:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/mindroom-frontend:buildcache,mode=max