name: Build MindRoom Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'Dockerfile.frontend'
      - '.github/workflows/mindroom-frontend.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'Dockerfile.frontend'
      - '.github/workflows/mindroom-frontend.yml'
  workflow_dispatch:

env:
  REGISTRY: git.nijho.lt
  REGISTRY_USER: basnijholt

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Run type checking
        working-directory: frontend
        run: pnpm run type-check || true  # Allow to fail for now

      - name: Run linting
        working-directory: frontend
        run: pnpm run lint || true  # Allow to fail for now

      - name: Build frontend
        working-directory: frontend
        run: pnpm run build

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: always()  # Run even if tests fail

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/mindroom-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
