"""Public hook system exports."""

from .context import (
    AfterResponseContext,
    AgentLifecycleContext,
    BeforeResponseContext,
    ConfigReloadedContext,
    CustomEventContext,
    HookContext,
    MessageEnrichContext,
    MessageEnvelope,
    MessageReceivedContext,
    ReactionReceivedContext,
    ResponseDraft,
    ResponseResult,
    ScheduleFiredContext,
)
from .decorators import hook
from .enrichment import (
    compute_enrichment_digest,
    render_enrichment_block,
    strip_enrichment_block,
    strip_enrichment_from_session_storage,
)
from .execution import emit, emit_collect, emit_transform
from .registry import HookRegistry
from .sender import (
    HookMessageSender,
    clear_hook_message_sender,
    get_hook_message_sender,
    set_hook_message_sender,
)
from .types import (
    BUILTIN_EVENT_NAMES,
    EVENT_AGENT_STARTED,
    EVENT_AGENT_STOPPED,
    EVENT_CONFIG_RELOADED,
    EVENT_MESSAGE_AFTER_RESPONSE,
    EVENT_MESSAGE_BEFORE_RESPONSE,
    EVENT_MESSAGE_ENRICH,
    EVENT_MESSAGE_RECEIVED,
    EVENT_REACTION_RECEIVED,
    EVENT_SCHEDULE_FIRED,
    EnrichmentItem,
    RegisteredHook,
)

__all__ = [
    "BUILTIN_EVENT_NAMES",
    "EVENT_AGENT_STARTED",
    "EVENT_AGENT_STOPPED",
    "EVENT_CONFIG_RELOADED",
    "EVENT_MESSAGE_AFTER_RESPONSE",
    "EVENT_MESSAGE_BEFORE_RESPONSE",
    "EVENT_MESSAGE_ENRICH",
    "EVENT_MESSAGE_RECEIVED",
    "EVENT_REACTION_RECEIVED",
    "EVENT_SCHEDULE_FIRED",
    "AfterResponseContext",
    "AgentLifecycleContext",
    "BeforeResponseContext",
    "ConfigReloadedContext",
    "CustomEventContext",
    "EnrichmentItem",
    "HookContext",
    "HookMessageSender",
    "HookRegistry",
    "MessageEnrichContext",
    "MessageEnvelope",
    "MessageReceivedContext",
    "ReactionReceivedContext",
    "RegisteredHook",
    "ResponseDraft",
    "ResponseResult",
    "ScheduleFiredContext",
    "clear_hook_message_sender",
    "compute_enrichment_digest",
    "emit",
    "emit_collect",
    "emit_transform",
    "get_hook_message_sender",
    "hook",
    "render_enrichment_block",
    "set_hook_message_sender",
    "strip_enrichment_block",
    "strip_enrichment_from_session_storage",
]
