"""One schema definition rendered for both durable backends.

The journal, projection, and outbox exist once as SQL. A dialect supplies only
the handful of spellings SQLite and PostgreSQL genuinely disagree about, so
neither backend can drift into its own behavior.
"""

from __future__ import annotations

from dataclasses import dataclass

PENDING_STATE = "pending"
SETTLED_STATE = "settled"


@dataclass(frozen=True, slots=True)
class Dialect:
    """The spellings that differ between the two supported backends."""

    name: str
    placeholder: str
    # A surrogate receipt-order key that is never reused after deletion,
    # because replay ordering and refresh tokens are both derived from it.
    receipt_order_column: str
    # Text that participates in ordering or range comparison. PostgreSQL's
    # default locale can order text differently from SQLite and from Python,
    # so any column a cursor compares is pinned to byte order explicitly.
    ordered_text: str


SQLITE_DIALECT = Dialect(
    name="sqlite",
    placeholder="?",
    receipt_order_column="INTEGER PRIMARY KEY AUTOINCREMENT",
    ordered_text="TEXT",
)

POSTGRES_DIALECT = Dialect(
    name="postgresql",
    placeholder="%s",
    receipt_order_column="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ordered_text='TEXT COLLATE "C"',
)


_TABLES = (
    """
    CREATE TABLE IF NOT EXISTS journal_events (
        receipt_order {receipt_order_column},
        principal_id TEXT NOT NULL,
        event_id {ordered_text} NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        event_class TEXT NOT NULL,
        sender TEXT NOT NULL,
        origin_server_ts BIGINT NOT NULL,
        source_json TEXT NOT NULL,
        semantic_consumer TEXT,
        membership_epoch BIGINT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('pending', 'settled')),
        outcome TEXT,
        created_at_ns BIGINT NOT NULL,
        settled_at_ns BIGINT,
        UNIQUE (principal_id, event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS visible_messages (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        logical_event_id {ordered_text} NOT NULL,
        thread_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        created_ts BIGINT NOT NULL,
        revision_event_id {ordered_text} NOT NULL,
        revision_ts BIGINT NOT NULL,
        content_json TEXT,
        refresh_token BIGINT,
        membership_epoch BIGINT NOT NULL,
        -- Set on a row this bot seeded from its own send, whose ordering
        -- metadata is a local guess: a Matrix send response carries only the
        -- event ID, and `origin_server_ts` is the server's to assign. The
        -- self-authored sync echo replaces those values and clears this.
        provisional INTEGER NOT NULL DEFAULT 0,
        -- Set when the *currently installed revision* was seeded locally, which
        -- is a different fact from the row being provisional: an authoritative
        -- original can carry a locally seeded edit on top of it. Only this
        -- tells a canonicalizing echo apart from a stale late seed of the same
        -- revision, which are otherwise identical by event ID.
        revision_provisional INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id, logical_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS unresolved_edits (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        target_event_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        edit_event_id {ordered_text} NOT NULL,
        edit_ts BIGINT NOT NULL,
        thread_id TEXT NOT NULL,
        content_json TEXT NOT NULL,
        PRIMARY KEY (principal_id, room_id, target_event_id, sender)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS redaction_tombstones (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        redacted_event_id TEXT NOT NULL,
        receipt_order BIGINT NOT NULL,
        PRIMARY KEY (principal_id, room_id, redacted_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS room_membership (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        PRIMARY KEY (principal_id, room_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS conversation_hydration (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        PRIMARY KEY (principal_id, room_id, thread_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS response_outbox (
        principal_id TEXT NOT NULL,
        turn_id TEXT NOT NULL,
        stage TEXT NOT NULL CHECK (stage IN ('initial', 'final')),
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        transaction_id TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        edits_event_id TEXT,
        attempted INTEGER NOT NULL DEFAULT 0,
        acknowledged_event_id TEXT,
        created_at_ns BIGINT NOT NULL,
        PRIMARY KEY (principal_id, turn_id, stage)
    )
    """,
)


_INDEXES = (
    """
    CREATE INDEX IF NOT EXISTS journal_events_pending
    ON journal_events (principal_id, receipt_order)
    WHERE state = 'pending'
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_page
    ON visible_messages (principal_id, room_id, thread_id, created_ts, logical_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_revision
    ON visible_messages (principal_id, room_id, revision_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_refresh
    ON visible_messages (principal_id, room_id, thread_id)
    WHERE refresh_token IS NOT NULL
    """,
    """
    CREATE INDEX IF NOT EXISTS response_outbox_unacknowledged
    ON response_outbox (principal_id, created_at_ns)
    WHERE acknowledged_event_id IS NULL
    """,
)


def schema_statements(dialect: Dialect) -> tuple[str, ...]:
    """Return every DDL statement needed to create the schema."""
    return tuple(
        statement.format(
            receipt_order_column=dialect.receipt_order_column,
            ordered_text=dialect.ordered_text,
        )
        for statement in (*_TABLES, *_INDEXES)
    )


def render(sql: str, dialect: Dialect) -> str:
    """Return SQL with parameter placeholders spelled for one backend.

    Statements are authored with ``?`` and never contain a literal string, so
    substitution cannot touch anything but a parameter marker.
    """
    if "'?" in sql or "?'" in sql:
        msg = "Event-journal SQL must not embed a literal question mark"
        raise ValueError(msg)
    if dialect.placeholder == "?":
        return sql
    return sql.replace("?", dialect.placeholder)
