"""One schema definition rendered for both durable backends.

The journal, projection, and outbox exist once as SQL. A dialect supplies only
the handful of spellings SQLite and PostgreSQL genuinely disagree about, so
neither backend can drift into its own behavior.
"""

from __future__ import annotations

from dataclasses import dataclass

_BYTE_ORDER_MARKER = "/*bytes*/"

PENDING_STATE = "pending"
SETTLED_STATE = "settled"


@dataclass(frozen=True, slots=True)
class Dialect:
    """The spellings that differ between the two supported backends."""

    name: str
    placeholder: str
    # A surrogate receipt-order key that is never reused after deletion,
    # because replay ordering and refresh tokens are both derived from it.
    receipt_order_column: str
    # Text that participates in ordering or range comparison. PostgreSQL's
    # default locale can order text differently from SQLite and from Python,
    # so any column a cursor compares is pinned to byte order explicitly.
    ordered_text: str
    # The same pin applied to an expression rather than a column declaration,
    # for columns that were already shipped unpinned and cannot be retyped
    # without rewriting the table.
    order_by_bytes: str


SQLITE_DIALECT = Dialect(
    name="sqlite",
    placeholder="?",
    receipt_order_column="INTEGER PRIMARY KEY AUTOINCREMENT",
    ordered_text="TEXT",
    # SQLite compares TEXT with BINARY unless told otherwise, which is already
    # byte order.
    order_by_bytes="",
)

POSTGRES_DIALECT = Dialect(
    name="postgresql",
    placeholder="%s",
    receipt_order_column="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ordered_text='TEXT COLLATE "C"',
    order_by_bytes=' COLLATE "C"',
)


_TABLES = (
    """
    CREATE TABLE IF NOT EXISTS journal_events (
        receipt_order {receipt_order_column},
        principal_id TEXT NOT NULL,
        event_id {ordered_text} NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        event_class TEXT NOT NULL,
        sender TEXT NOT NULL,
        origin_server_ts BIGINT NOT NULL,
        source_json TEXT NOT NULL,
        semantic_consumer TEXT,
        membership_epoch BIGINT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('pending', 'settled')),
        outcome TEXT,
        created_at_ns BIGINT NOT NULL,
        settled_at_ns BIGINT,
        UNIQUE (principal_id, event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS visible_messages (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        logical_event_id {ordered_text} NOT NULL,
        thread_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        created_ts BIGINT NOT NULL,
        revision_event_id {ordered_text} NOT NULL,
        revision_ts BIGINT NOT NULL,
        content_json TEXT,
        refresh_token BIGINT,
        membership_epoch BIGINT NOT NULL,
        PRIMARY KEY (principal_id, room_id, logical_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS unresolved_edits (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        target_event_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        edit_event_id {ordered_text} NOT NULL,
        edit_ts BIGINT NOT NULL,
        thread_id TEXT NOT NULL,
        content_json TEXT NOT NULL,
        PRIMARY KEY (principal_id, room_id, target_event_id, sender)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS redaction_tombstones (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        redacted_event_id TEXT NOT NULL,
        receipt_order BIGINT NOT NULL,
        PRIMARY KEY (principal_id, room_id, redacted_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS room_membership (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        -- A departure has been fenced and the bot has not been seen back in
        -- the room since. The bot cannot leave a room it is not in, so a
        -- second local departure while this holds is the same one arriving
        -- twice rather than a new one.
        departure_fenced INTEGER NOT NULL DEFAULT 0,
        -- Departures already fenced locally whose sync report has not arrived.
        -- A count rather than a flag: leave/rejoin/leave owes two reports, and
        -- one bit would let the second echo fence a membership it did not end.
        owed_departure_reports BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS conversation_hydration (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        -- Whether the walk that filled this conversation ran out of
        -- conversation rather than out of allowance. Being hydrated and being
        -- complete are different facts: a walk that stopped at the prompt
        -- window is hydrated, and a reader whose correctness is completeness
        -- has to be able to tell that from a whole conversation.
        complete INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id, thread_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS response_outbox (
        principal_id TEXT NOT NULL,
        turn_id TEXT NOT NULL,
        stage TEXT NOT NULL CHECK (stage IN ('initial', 'final')),
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        transaction_id TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        edits_event_id TEXT,
        attempted INTEGER NOT NULL DEFAULT 0,
        acknowledged_event_id TEXT,
        created_at_ns BIGINT NOT NULL,
        PRIMARY KEY (principal_id, turn_id, stage)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS approval_cards (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        card_event_id TEXT NOT NULL,
        card_json TEXT NOT NULL,
        -- The decision this bot committed to before it tried to show it. A
        -- card is answered the moment this is set, whether or not the edit
        -- carrying it reached the room.
        resolution_json TEXT,
        membership_epoch BIGINT NOT NULL,
        created_at_ns BIGINT NOT NULL,
        PRIMARY KEY (principal_id, card_event_id)
    )
    """,
)


_INDEXES = (
    """
    CREATE INDEX IF NOT EXISTS journal_events_pending
    ON journal_events (principal_id, receipt_order)
    WHERE state = 'pending'
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_page
    ON visible_messages (principal_id, room_id, thread_id, created_ts, logical_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_revision
    ON visible_messages (principal_id, room_id, revision_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_refresh
    ON visible_messages (principal_id, room_id, thread_id)
    WHERE refresh_token IS NOT NULL
    """,
    """
    CREATE INDEX IF NOT EXISTS response_outbox_unacknowledged
    ON response_outbox (principal_id, created_at_ns)
    WHERE acknowledged_event_id IS NULL
    """,
    """
    CREATE INDEX IF NOT EXISTS approval_cards_room
    ON approval_cards (principal_id, room_id, created_at_ns)
    """,
)


# Columns added to a table after it first shipped. `CREATE TABLE IF NOT EXISTS`
# leaves an existing table exactly as it is, so a database created before one of
# these columns existed keeps working right up until the first statement that
# names it, and then fails at runtime rather than at startup. Every column added
# to an existing table has to be listed here as well as in the table above.
_ADDED_COLUMNS: tuple[tuple[str, str, str], ...] = (
    ("approval_cards", "resolution_json", "TEXT"),
    ("room_membership", "departure_fenced", "INTEGER NOT NULL DEFAULT 0"),
    ("room_membership", "owed_departure_reports", "BIGINT NOT NULL DEFAULT 0"),
    # A row that predates this column was written by a walk that stopped at the
    # prompt window as often as not, so the default has to be the conservative
    # answer. Claiming completeness for a conversation nobody measured is the
    # one direction that silently serves a truncated read.
    ("conversation_hydration", "complete", "INTEGER NOT NULL DEFAULT 0"),
)


def added_columns() -> tuple[tuple[str, str, str], ...]:
    """Return every (table, column, definition) that may predate a database."""
    return _ADDED_COLUMNS


def add_column_statement(table: str, column: str, definition: str, *, if_not_exists: bool = False) -> str:
    """Return the DDL that adds one column to an existing table.

    PostgreSQL can guard the add itself; SQLite cannot, and its caller checks
    the existing columns first instead.
    """
    guard = "IF NOT EXISTS " if if_not_exists else ""
    return f"ALTER TABLE {table} ADD COLUMN {guard}{column} {definition}"


def schema_statements(dialect: Dialect) -> tuple[str, ...]:
    """Return every DDL statement needed to create the schema."""
    return tuple(
        statement.format(
            receipt_order_column=dialect.receipt_order_column,
            ordered_text=dialect.ordered_text,
        )
        for statement in (*_TABLES, *_INDEXES)
    )


def render(sql: str, dialect: Dialect) -> str:
    """Return SQL with parameter placeholders spelled for one backend.

    Statements are authored with ``?`` and never contain a literal string, so
    substitution cannot touch anything but a parameter marker.
    """
    if "'?" in sql or "?'" in sql:
        msg = "Event-journal SQL must not embed a literal question mark"
        raise ValueError(msg)
    # Substitution is a plain string rewrite, so a marker inside an authored
    # string literal would be rewritten as if it were an identifier. No
    # statement has one and no user value reaches here -- values are bound
    # separately by both backends -- but the rewriter cannot tell, so the
    # adjacency is rejected rather than trusted, the same way a literal
    # question mark is.
    if f"'{_BYTE_ORDER_MARKER}" in sql or f"{_BYTE_ORDER_MARKER}'" in sql:
        msg = "Event-journal SQL must not embed the byte-order marker in a literal"
        raise ValueError(msg)
    sql = sql.replace(_BYTE_ORDER_MARKER, dialect.order_by_bytes)
    if dialect.placeholder == "?":
        return sql
    return sql.replace("?", dialect.placeholder)
