"""API endpoints for tools information."""

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter(prefix="/api/tools", tags=["tools"])


class ToolsResponse(BaseModel):
    """Response containing all registered tools."""

    tools: list[dict]


@router.get("")
async def get_registered_tools() -> ToolsResponse:
    """Get all registered tools from mindroom.

    This reads from a pre-generated JSON file that is created by the test suite.
    The JSON file is generated by tests/test_tools_metadata.py and committed to the repo.
    """
    # Path to the generated JSON file
    json_path = Path(__file__).parent.parent.parent.parent.parent / "mindroom/tools_metadata.json"

    if not json_path.exists():
        raise HTTPException(
            status_code=500,
            detail="tools_metadata.json not found. Run 'pytest tests/test_tools_metadata.py' to generate it.",
        )

    with json_path.open() as f:
        data = json.load(f)
        return ToolsResponse(tools=data["tools"])
