"""API endpoints for tools information."""

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from mindroom.credentials import get_credentials_manager

router = APIRouter(prefix="/api/tools", tags=["tools"])


class ToolsResponse(BaseModel):
    """Response containing all registered tools."""

    tools: list[dict]


@router.get("")
async def get_registered_tools() -> ToolsResponse:
    """Get all registered tools from mindroom.

    This reads from a pre-generated JSON file that is created by the test suite.
    The JSON file is generated by tests/test_tools_metadata.py and committed to the repo.
    It also checks if credentials exist for tools that require them.
    """
    # Path to the generated JSON file
    json_path = Path(__file__).parent.parent.parent.parent.parent / "mindroom/tools_metadata.json"

    if not json_path.exists():
        raise HTTPException(
            status_code=500,
            detail="tools_metadata.json not found. Run 'pytest tests/test_tools_metadata.py' to generate it.",
        )

    with json_path.open() as f:
        data = json.load(f)
        tools = data["tools"]

    # Get credentials manager to check if tools are configured
    manager = get_credentials_manager()

    # Update status for tools that require configuration
    for tool in tools:
        if tool.get("status") == "requires_config" and tool.get("config_fields"):
            # Check if all required fields have credentials
            credentials = manager.load_credentials(tool["name"])
            if credentials:
                # Check if all required fields are present
                required_fields = [
                    field["name"] for field in tool.get("config_fields", []) if field.get("required", True)
                ]
                if all(field in credentials for field in required_fields):
                    # Tool is configured!
                    tool["status"] = "available"

    return ToolsResponse(tools=tools)
