"""API endpoints for tools information."""

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter(prefix="/api/tools", tags=["tools"])


class ToolsResponse(BaseModel):
    """Response containing all registered tools."""

    tools: list[dict]


@router.get("")
async def get_registered_tools() -> ToolsResponse:
    """Get all registered tools from mindroom.

    This reads from a pre-generated JSON file that is created by the test suite.
    The JSON file is generated by tests/test_tools_metadata.py and committed to the repo.
    """
    # Path to the generated JSON file
    json_path = Path(__file__).parent.parent.parent.parent.parent / "mindroom/tools_metadata.json"

    if not json_path.exists():
        raise HTTPException(
            status_code=500,
            detail="tools_metadata.json not found. Run 'pytest tests/test_tools_metadata.py' to generate it.",
        )

    with json_path.open() as f:
        data = json.load(f)
        return ToolsResponse(tools=data["tools"])


@router.get("/check-frontend-coverage")
async def check_frontend_coverage() -> dict:
    """Check which tools are in backend but missing from frontend."""
    # Load the backend tools from JSON
    json_path = Path(__file__).parent.parent.parent.parent.parent / "mindroom/tools_metadata.json"

    if not json_path.exists():
        raise HTTPException(
            status_code=500,
            detail="tools_metadata.json not found. Run 'pytest tests/test_tools_metadata.py' to generate it.",
        )

    with json_path.open() as f:
        data = json.load(f)
        backend_tools = {tool["name"] for tool in data["tools"]}

    # These are the tools currently shown in the frontend
    # We'll get this list from the frontend in a real implementation
    frontend_tools = {
        "google",  # Gmail
        "outlook",
        "yahoo",
        "calendar",
        "amazon",
        "walmart",
        "ebay",
        "target",
        "imdb",
        "spotify",
        "netflix",
        "youtube",
        "apple_music",
        "hbo",
        "twitter",
        "facebook",
        "instagram",
        "reddit",
        "linkedin",
        "slack",
    }

    # Map some tool names to their frontend equivalents
    tool_name_mapping = {
        "gmail": "google",  # Gmail is shown as "Google Services"
        "x": "twitter",  # X is shown as Twitter
    }

    # Apply name mappings
    mapped_backend = set()
    for tool in backend_tools:
        mapped_name = tool_name_mapping.get(tool, tool)
        mapped_backend.add(mapped_name)

    # Find tools that are in backend but not in frontend
    missing_in_frontend = backend_tools - frontend_tools
    # Exclude tools that have mappings
    missing_in_frontend = {t for t in missing_in_frontend if tool_name_mapping.get(t, t) not in frontend_tools}

    # Find tools that are in frontend but not in backend
    missing_in_backend = frontend_tools - mapped_backend

    return {
        "backend_tools": sorted(backend_tools),
        "frontend_tools": sorted(frontend_tools),
        "missing_in_frontend": sorted(missing_in_frontend),
        "missing_in_backend": sorted(missing_in_backend),
        "total_backend": len(backend_tools),
        "total_frontend": len(frontend_tools),
    }
