"""Generate the hosted SaaS instance seed config from the `mindroom config init` starter.

Run from the repository root with `uv run python scripts/sync_config.py`.
"""

import sys
from pathlib import Path

import yaml

from mindroom import model_defaults
from mindroom.cli.config import _full_template

ROOT_DIR = Path(__file__).parent.parent
TARGET_PATH = ROOT_DIR / "cluster" / "k8s" / "instance" / "default-config.yaml"
HEADER = """\
# Hosted MindRoom instance seed config.
# Generated by scripts/sync_config.py from the `mindroom config init` OpenRouter starter; do not edit by hand.
"""


def saas_config() -> dict:
    """Return the config init starter adapted to hosted SaaS instances."""
    template = _full_template("openrouter", matrix_server="self-hosted")
    config = yaml.safe_load(template)

    # Hosted tenants choose from the central OpenRouter presets in the dashboard.
    config["models"] = {name: preset.to_config_dict() for name, preset in model_defaults.SAAS_MODEL_PRESETS.items()}
    config["router"]["model"] = "luna"

    # The instance image does not ship sentence_transformers (torch), and Hobby/Pro
    # tenants may only have an OpenRouter key, so semantic memory search embeds via OpenRouter.
    config["memory"]["embedder"] = {
        "provider": "openai",
        "config": {
            "model": model_defaults.OPENROUTER_OPENAI_EMBEDDING_SMALL,
            "host": model_defaults.OPENROUTER_BASE_URL_DEFAULT,
            "credentials_service": "openrouter",
            "dimensions": model_defaults.OPENAI_EMBEDDING_DIMENSIONS[model_defaults.OPENAI_EMBEDDING_SMALL],
        },
    }

    # An explicit worker_tools list overrides the chart's sandbox routing, and [] would run
    # shell/file/python in the primary pod beside tenant credentials.
    config["defaults"].pop("worker_tools", None)

    # Voice messages transcribe through OpenRouter's OpenAI-compatible endpoint with the tenant's OpenRouter key.
    config["voice"] = {
        "enabled": True,
        "stt": {
            "provider": "openai_compatible",
            "model": model_defaults.OPENROUTER_OPENAI_TRANSCRIPTION,
            "host": model_defaults.OPENROUTER_BASE_URL_DEFAULT,
            "credentials_service": "openrouter",
        },
    }

    # The platform upgrades hosted instances, so tenants cannot act on update notices.
    # Hosted agents also learn workspace skills from their conversations.
    config["defaults"]["tools"].remove("update_awareness")
    for agent in config["agents"].values():
        agent["tools"].remove("update_awareness")
        agent["skill_learning"] = {"enabled": True}
    return config


def main() -> int:
    """Write the hosted seed config."""
    body = yaml.dump(saas_config(), default_flow_style=False, sort_keys=False, allow_unicode=True, width=120)
    TARGET_PATH.write_text(HEADER + body, encoding="utf-8")
    print(f"✅ Wrote {TARGET_PATH.relative_to(ROOT_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
